---
title: "R Notebook"
output: html_notebook
---

```{r}
x<-matrix(runif(250000,0,1),25,10000)
Y<- matrix(rep(0,250000),25,10000)
Y[1,]<-x[1,]
for(i in 2:25)
{
  Y[i,]<-Y[i-1,]+x[i,]
}
myData = data.frame(Y[1,],Y[2,],Y[3,],Y[4,],Y[5,],Y[6,],Y[7,],Y[8,],Y[9,],Y[10,],Y[11,],Y[12,],Y[13,],Y[14,],Y[15,],Y[16,],Y[17,],Y[18,],Y[19,],Y[20,],Y[21,],Y[22,],Y[23,],Y[24,],Y[25,])
dens = apply(myData, 2, density)
plot(NA, xlim=range(sapply(dens, "[", "x")), ylim=range(sapply(dens, "[","y")))
mapply(lines, dens, col=1:length(dens))
```


```{r}
x<-matrix(rnorm(250000,mean=0,sd=1),25,10000)
Y<- matrix(rep(0,250000),25,10000)
Y[1,]<-x[1,]
for(i in 2:25)
{
  Y[i,]<-Y[i-1,]+x[i,]
}
myData = data.frame(Y[1,],Y[2,],Y[3,],Y[4,],Y[5,],Y[6,],Y[7,],Y[8,],Y[9,],Y[10,],Y[11,],Y[12,],Y[13,],Y[14,],Y[15,],Y[16,],Y[17,],Y[18,],Y[19,],Y[20,],Y[21,],Y[22,],Y[23,],Y[24,],Y[25,])
dens = apply(myData, 2, density)
plot(NA, xlim=range(sapply(dens, "[", "x")), ylim=range(sapply(dens, "[","y")))
mapply(lines, dens, col=1:length(dens))
```

```{r}
x<-matrix(rexp(250000),25,10000)
Y<- matrix(rep(0,250000),25,10000)
Y[1,]<-x[1,]
for(i in 2:25)
{
  Y[i,]<-Y[i-1,]+x[i,]
}
myData = data.frame(Y[1,],Y[2,],Y[3,],Y[4,],Y[5,],Y[6,],Y[7,],Y[8,],Y[9,],Y[10,],Y[11,],Y[12,],Y[13,],Y[14,],Y[15,],Y[16,],Y[17,],Y[18,],Y[19,],Y[20,],Y[21,],Y[22,],Y[23,],Y[24,],Y[25,])
dens = apply(myData, 2, density)
plot(NA, xlim=range(sapply(dens, "[", "x")), ylim=range(sapply(dens, "[","y")))
mapply(lines, dens, col=1:length(dens))
```

```{r}
x1<- runif(10000,-1,1)
hist(x1)
x2<-2*x1
hist(x2)
x3<-x1+x2+3
hist(x3)

```

```{r}
x1<- rnorm(10000,mean=-1,sd=1)
hist(x1)
x2<-2*x1
hist(x2)
x3<-x1+x2+3
hist(x3)
```
```{r}
data1<- rnorm(100,mean=5.027,sd=0.1)
library(ggplot2)
data2<- rnorm(100,mean=5,sd=0.1)
z=(mean(data1)-5)*100
prob = pnorm(z,lower.tail = FALSE) 
print(2*prob)
#not supporting conjecture
```
```{r}
data2<- rnorm(100,mean=5,sd=0.1)
z=(mean(data2)-5)*100
prob = pnorm(z,lower.tail = FALSE) 
print(2*prob)
```
```{r}
data3<- rnorm(10000,mean=6,sd=0.1)
z=(mean(data3)-5)*1000
prob = pnorm(z,lower.tail = FALSE) 
print(2*prob)
```

```{r}
data3<- rnorm(10000,mean=5.001,sd=0.1)
z=(mean(data3)-5)*1000
prob = pnorm(z,lower.tail = FALSE) 
print(2*prob)
```

```{r}
data3<- rnorm(10000,mean=5,sd=0.1)
z=(mean(data3)-5)*1000
prob = pnorm(z,lower.tail = FALSE) 
print(2*prob)
```
ʼ
```{r}
#quest3
d1<- rnorm(20,mean=5,sd=1)
d2<- rnorm(24,mean=3,sd=1)
meand1<-mean(d1)
meand2<-mean(d2)
z=(meand1-meand2)-(5-3)
z=z/(sqrt((1/20) + (1/24)))
z
prob = pnorm(z,lower.tail = FALSE) 
print(prob)
```


```{r}
d1<- rnorm(40,mean=5,sd=1)
d2<- rnorm(64,mean=3,sd=1)
meand1<-mean(d1)
meand2<-mean(d2)
z=(meand1-meand2)-(5-3)
z=z/(sqrt((1/40) + (1/64)))
z
prob = pnorm(z,lower.tail = FALSE) 
print(prob)
```


```{r}
d1<- rexp(40,1/5)
d2<- rexp(64,1/3)
meand1<-mean(d1)
meand2<-mean(d2)
z=(meand1-meand2)-(5-3)
z=z/(sqrt((1/40) + (1/64)))
z
prob = pnorm(z,lower.tail = FALSE) 
print(prob)
```

```{r}
d1<- rexp(20,1/5)
d2<- rexp(24,1/3)
meand1<-mean(d1)
meand2<-mean(d2)
z=(meand1-meand2)-(5-3)
z=z/(sqrt((1/20) + (1/24)))
z
prob = pnorm(z,lower.tail = FALSE) 
print(prob)
```

